
["Configs for SeasonHUD"]

	["Configs for SeasonHUD"."HUD:"]
		#Enable the Debug hud for testing? 
		# (true/false)
		enable_debug_hud = false
		#Show sub-season (i.e. Early Winter, Late Autumn) instead of basic season? 
		# (true/false)
		enable_show_sub_season = true
		#Show the current day of the season/sub-season? 
		# (true/false)
		enable_show_day = true

